@echo off
REM ===========================================================================
REM  Souq Bartaa - ONE-CLICK run for the current agent session.
REM  Double-click this file once, then leave it alone.
REM
REM  NO DOCKER is touched anywhere in here. The stack is scripts\dev-native.ts,
REM  exactly as START-HERE.cmd runs it: embedded postgres in-process, no redis,
REM  mail captured to .tmp\dev-mail.json.
REM
REM  What it does, in order (REORDERED 2026-09-07 - see the long note further
REM  down; the suite now runs with nothing else competing for the machine):
REM    1. downloads the Rubik arabic-subset woff2 pair (Phase 11 / Q32)
REM    2. records git state
REM    3. typecheck + lint
REM    4. the full test suite, ALONE
REM    5. opens the platform in a SECOND window (keep that one open)
REM    6. waits for the dev cluster, then `prisma migrate status`
REM
REM  Everything lands in agent-report.log. Every section records its own exit
REM  code and the run CONTINUES after a failure, so one red check does not hide
REM  the others.
REM ===========================================================================

cd /d "%~dp0"
set LOG=agent-report.log

REM  The test harness boots its OWN postgres. 5433 sits above the dev cluster's
REM  5432 and below the Hyper-V reserved ranges - same reason as QA-CHECK.cmd.
set EMBEDDED_PG_PORT=5433

REM ===========================================================================
REM  DO NOT EDIT THIS FILE WHILE A RUN IS OPEN - not even a window sitting at
REM  "Press any key to continue".
REM
REM  cmd.exe does not read a batch file into memory. It reads it incrementally
REM  and remembers a BYTE OFFSET, so editing the file mid-run makes the next
REM  line it reads come from a different place in the new text. On 2026-09-07
REM  that produced a paused window which, on the keypress, printed
REM
REM    'stack' is not recognized as an internal or external command
REM
REM  - the offset had landed inside "Leave the OTHER window (the stack)
REM  running." - and then re-executed steps 4 to 6, starting a second stack.
REM  Nothing was corrupted (the sweep had already finished and written its log)
REM  but the output was nonsense, and a nonsense failure is expensive precisely
REM  because it looks like a real one.
REM
REM  The `exit /b 0` at the very bottom is the only guard batch allows: it caps
REM  the damage when a resumed offset lands past the end of the real work.
REM ===========================================================================

REM ---------------------------------------------------------------------------
REM  REFUSE TO START IF A STACK IS ALREADY UP. Added 2026-09-07 after the fix
REM  below created a second-order version of the bug it solved.
REM
REM  Moving the stack to the END of the sweep stopped it competing with the suite
REM  WITHIN a run - and left every run finishing with a stack still listening, so
REM  the NEXT sweep started against exactly the contention the reorder removed.
REM  The symptom is a genuine Postgres backend crash mid-suite, surfacing as
REM  "Can't reach database server at 127.0.0.1:5433" in whichever concurrency
REM  test happened to be running: 20-way checkout, 10-way checkout, whichever.
REM
REM  A note in the docs would not have helped - the whole point of a one-click
REM  script is that nobody reads the docs first. So the script checks, and says
REM  what to do. Deterministic beats unlikely.
REM ---------------------------------------------------------------------------
netstat -ano | findstr /r /c:"LISTENING" | findstr /c:":3000 " >nul 2>&1
if %ERRORLEVEL%==0 (
  echo.
  echo   ================================================================
  echo    A stack is already running on port 3000.
  echo.
  echo    Close the "Souq Bartaa - stack (keep open)" window first, then
  echo    run this again. The test suite boots its own database, and a
  echo    second cluster plus "next dev" competing for the machine is what
  echo    crashes it mid-run.
  echo   ================================================================
  echo.
  pause
  exit /b 1
)

echo Souq Bartaa agent sweep - %DATE% %TIME% > %LOG%
echo. >> %LOG%

echo.
echo   [1/6] fetching the Rubik arabic subset ...
echo =============== FETCH-RUBIK =============== >> %LOG%
call node scripts\fetch-rubik.mjs >> %LOG% 2>&1
echo EXITCODE=%ERRORLEVEL% >> %LOG%
echo. >> %LOG%

echo   [2/6] recording git state ...
echo =============== GIT BRANCH + STATUS =============== >> %LOG%
call git status --branch --porcelain=v1 >> %LOG% 2>&1
echo. >> %LOG%
echo =============== GIT LOG (last 20) =============== >> %LOG%
call git log --oneline -20 >> %LOG% 2>&1
echo. >> %LOG%
echo =============== GIT DIFF --STAT =============== >> %LOG%
call git diff --stat >> %LOG% 2>&1
echo. >> %LOG%

echo   [3/6] typecheck + lint ...
echo =============== TYPECHECK =============== >> %LOG%
call pnpm typecheck >> %LOG% 2>&1
echo EXITCODE=%ERRORLEVEL% >> %LOG%
echo. >> %LOG%

echo =============== LINT =============== >> %LOG%
call pnpm lint >> %LOG% 2>&1
echo EXITCODE=%ERRORLEVEL% >> %LOG%
echo. >> %LOG%

REM ---------------------------------------------------------------------------
REM  THE SUITE RUNS ALONE. This is the 2026-09-07 fix, and it is the whole reason
REM  the order above changed.
REM
REM  The stack used to start in step 2, BEFORE the suite - so `pnpm test`, which
REM  boots its own embedded cluster on 5433, ran alongside a second embedded
REM  cluster on 5432 plus `next dev` plus the worker. Two Postgres servers and a
REM  dev server competing for one Windows box, and the symptom was a genuine
REM  backend crash mid-suite:
REM
REM    background writer process (PID ...) exited with exit code 1
REM    terminating any other active server processes
REM    all server processes terminated; reinitializing
REM
REM  followed by "Can't reach database server at 127.0.0.1:5433" in whichever
REM  test happened to be running - usually the 10-way concurrent checkout, being
REM  the heaviest. It failed on three sweeps of five and passed on the other two,
REM  on identical code, which is exactly what resource starvation looks like.
REM
REM  The same overlap explains the OTHER recurring false alarm: `prisma migrate
REM  status` reported "FATAL: the database system is starting up" because it ran
REM  seconds after the stack was launched, against a cluster still booting. It is
REM  now after the stack AND after a readiness wait.
REM ---------------------------------------------------------------------------

echo   [4/6] tests ... (this is the long one, several minutes - nothing else is running)
echo =============== TEST =============== >> %LOG%
call pnpm test >> %LOG% 2>&1
echo EXITCODE=%ERRORLEVEL% >> %LOG%
echo. >> %LOG%

echo   [5/6] starting the platform in a second window ...
start "Souq Bartaa - stack (keep open)" cmd /c "%~dp0START-HERE.cmd"

echo   [6/6] waiting for the dev cluster, then checking migrations ...
REM  Poll rather than sleep a fixed amount: the cluster takes anywhere from two
REM  seconds to half a minute depending on what else the machine is doing, and a
REM  fixed `timeout` is either a flake or wasted time. Twelve tries at 5s = 60s.
set MIGRATE_TRIES=0
:waitpg
set /a MIGRATE_TRIES+=1
timeout /t 5 /nobreak >nul
call pnpm exec prisma migrate status >"%TEMP%\sb-migrate-status.txt" 2>&1
set MIGRATE_EXIT=%ERRORLEVEL%
if %MIGRATE_EXIT%==0 goto pgready
if %MIGRATE_TRIES% LSS 12 goto waitpg

:pgready
echo =============== PRISMA MIGRATE STATUS =============== >> %LOG%
echo (after %MIGRATE_TRIES% readiness attempt^(s^)) >> %LOG%
type "%TEMP%\sb-migrate-status.txt" >> %LOG% 2>&1
REM  The status command's OWN exit code, captured before `type` overwrote it - the
REM  bug this line exists to not have.
echo EXITCODE=%MIGRATE_EXIT% >> %LOG%
del "%TEMP%\sb-migrate-status.txt" >nul 2>&1
echo. >> %LOG%

echo === done === >> %LOG%
echo.
echo   Done. Results are in agent-report.log
echo   Leave the OTHER window - the stack - running.
echo.
pause
REM  See the warning at the top: this caps what a resumed byte offset can run.
exit /b 0
