import type { CSSProperties } from 'react';
import type { Metadata } from 'next';
import { cookies, headers } from 'next/headers';
import { notFound } from 'next/navigation';
import { getEnv } from '@/env';
import { recordConsentedEvents } from '@/server/analytics';
import { PUBLIC_ACTOR, tenantDb } from '@/server/db';
import { can } from '@/server/entitlements';
import { getClientIp } from '@/server/http/get-client-ip';
import { SEARCH_PAGE_SIZE, searchProducts } from '@/server/search';
import { t } from '@/shared/i18n';
import { analyticsDecision, pluralCount, ProductCard, StorefrontShell } from '@/templates';
import { SearchBox } from '@/templates/components/search-box';
import { CONSENT_COOKIE, readConsentCookie, visitorHash } from '../_data/consent';
import { loadStorefrontContext } from '../_data/context';
import { storefrontMetadata } from '../_data/metadata';
import { requireStorefront } from '../_data/surface';
import { queryProductsByIds } from './_data';

/**
 * `/search?q=…` — the storefront's product search.
 *
 * A PLAIN GET, no JavaScript. The form in `SearchBox` navigates here and this renders the answer,
 * for the same reason the category filter in `products/page.tsx` is a set of links: on Fast 3G, a
 * control that needs a bundle to work is a control that does not work — and search is what a visitor
 * reaches for when the page has already failed them once.
 *
 * BOTH GATES ARE RE-ASKED HERE. The section that draws the box is gated too, but a form left open in
 * a tab across a feature toggle, or a URL a customer bookmarked, must not reach a live route.
 * `notFound()` rather than a message: a screen that says "search is disabled for this shop" is an
 * inventory of what the platform sells, offered to a customer who did not ask.
 *
 * IT RECORDS ITS OWN SEARCH EVENT, and that is the point of doing it server-side rather than leaving
 * it to the beacon. A ZERO-RESULT SEARCH IS THE MOST ACTIONABLE NUMBER IN THE MERCHANT'S REPORT —
 * «هاي البنت دورت على شنطة وما لقيت» is a buying decision — and the visitor least likely to be
 * running our JavaScript is not less worth listening to. The count also has to come from the thing
 * that ran the query; a client-reported `resultCount` is a number a merchant would plan purchases
 * around, supplied by an untrusted caller.
 *
 * Recording still passes both gates (`recordConsentedEvents`): a search by a visitor who declined
 * measurement is not recorded, which is the correct trade and is stated in the privacy copy.
 */
export const dynamic = 'force-dynamic';

interface PageProps {
  /** `string | string[]`, because a repeated `?q=a&q=b` arrives as an array — see products/page.tsx. */
  searchParams: Promise<{ q?: string | string[] }>;
}

/** First value of a possibly-repeated parameter, trimmed to nothing-or-something. */
function firstParam(value: string | string[] | undefined): string {
  const raw = Array.isArray(value) ? value[0] : value;
  return (raw ?? '').trim();
}

/**
 * NO ARGUMENTS, and the omission is deliberate rather than an oversight.
 *
 * The obvious title for this page is «نتائج البحث عن "{q}"», and it is exactly what must not be
 * built: `q` is attacker-chosen text, the title is reflected into `<title>` and the OG tags, and
 * this route already renders for whoever types the URL. Since the page is `noindex` anyway (see
 * below), a query-bearing title buys nothing and hands a stranger a say in what the shop's own
 * metadata reads. The static title is the whole answer, so the parameter is not taken at all —
 * which is also what stops the next person wiring it in without noticing.
 */
export async function generateMetadata(): Promise<Metadata> {
  const surface = await requireStorefront();
  const context = await loadStorefrontContext(surface);

  return storefrontMetadata({
    context,
    title: t('insights', 'search.pageTitle'),
    path: '/search',
    suspended: surface.isSuspended,
    /**
     * NOINDEX, ALWAYS.
     *
     * A search results page is thin, duplicate content generated by whoever typed the URL, and an
     * indexable one is an open invitation to have a shop's own domain rank for words its owner never
     * wrote. Standard practice, and here it also stops a crawler manufacturing search events: a
     * crawled `?q=` would land in the merchant's report as a customer who looked for something.
     */
    noindex: true,
  });
}

export default async function SearchPage({ searchParams }: PageProps) {
  const surface = await requireStorefront();
  if (surface.isSuspended) return null;

  /**
   * Axis (a) plus the merchant's own switch. Resolved before anything else is read: a shop without
   * search has no reason to pay for a context load.
   *
   * `Site.searchEnabled` is read directly rather than through the storefront context because
   * `StorefrontFlags` does not carry it until the handoff diff lands — and this route must enforce
   * the gate today regardless of when that happens.
   */
  const featureAvailable = (await can(surface.tenantId, 'search_insights')) === true;
  if (!featureAvailable) notFound();

  const context = await loadStorefrontContext(surface);

  const site = await readSearchSwitch(surface.tenantId);
  if (!site) notFound();

  const raw = firstParam((await searchParams).q);
  const result = await searchProducts(surface.tenantId, raw, { take: SEARCH_PAGE_SIZE });
  const products = await queryProductsByIds(surface.tenantId, result.productIds);

  const requestHeaders = await headers();
  const consent = readConsentCookie((await cookies()).get(CONSENT_COOKIE)?.value);

  /**
   * A search is recorded only when the term was actually SEARCHED FOR.
   *
   * `tooShort` covers an empty box and a one-character query — landing on `/search` with no term is
   * navigation, not a search, and recording it would fill the merchant's report with a blank row
   * whose `zeroResults` count made it look like the most-missed product in the shop.
   */
  if (!result.tooShort) {
    const { ip } = getClientIp({ headers: requestHeaders });
    const userAgent = requestHeaders.get('user-agent');

    await recordConsentedEvents({
      tenantId: surface.tenantId,
      ip,
      userAgent,
      consentVisitorHash: visitorHash({ tenantId: surface.tenantId, ip, userAgent }),
      cookieGranted: consent.granted,
      featureEnabled: (await can(surface.tenantId, 'visitor_analytics')) === true,
      events: [
        {
          kind: 'search',
          path: '/search',
          // The NORMALISED term, so the report groups «الفستان» and «فستان» as one. `recordEvents`
          // normalises again — idempotent by construction, see `normaliseSearchTerm`.
          searchTerm: result.term,
          // The server's own count. This is the number the whole feature exists to produce.
          resultCount: result.total,
        },
      ],
    });
  }

  const analytics = analyticsDecision({
    featureEnabled: context.flags.analytics,
    consentGranted: consent.granted,
    websiteId: context.site.umamiWebsiteId,
    scriptUrl: getEnv().UMAMI_SCRIPT_URL,
  });

  const columns = context.template.layout.gridColumns;

  return (
    <StorefrontShell context={context} analytics={analytics} consentAnswered={consent.answered}>
      <section className="sf-block">
        <div className="sf-shell">
          <div className="sf-block__head">
            <h1 className="sf-block__title">{t('insights', 'search.pageTitle')}</h1>
            {result.term ? (
              <p className="sf-block__lead">{pluralCount('products.count', result.total)}</p>
            ) : null}
          </div>

          <SearchBox
            labels={{
              field: t('insights', 'search.field'),
              placeholder: t('insights', 'search.placeholder'),
              submit: t('insights', 'search.submit'),
              region: t('insights', 'search.region'),
            }}
            /*
              The RAW term, not the normalised one. A visitor who typed «الفستان» should find their
              own words in the box when the page comes back — showing them «فستان» reads as the shop
              silently correcting them, and it makes an edit-and-retry confusing.
            */
            defaultValue={raw}
            id="sf-search-results"
          />

          {/*
            THREE outcomes, three sentences. «ما في نتائج» for a search that ran and found nothing is
            true; saying it for an empty box or a one-letter query is not, and it sends the visitor
            looking for a product that may well be there.
          */}
          {result.tooShort ? (
            <p className="sf-note" style={{ marginBlockStart: 'var(--t-space-xl)' }}>
              {raw === '' ? t('insights', 'search.prompt') : t('insights', 'search.tooShort')}
            </p>
          ) : products.length === 0 ? (
            <div style={{ marginBlockStart: 'var(--t-space-xl)' }}>
              {/*
                The term is VISITOR INPUT and is rendered as a text node through an i18n parameter.
                React escapes it; nothing here interpolates it into markup, and there is no
                `dangerouslySetInnerHTML` anywhere on this path. The same discipline applies on the
                merchant's report, where the same string is shown back to the shop owner.
              */}
              <p className="sf-note">{t('insights', 'search.empty', { term: result.term })}</p>
              <p className="sf-note">
                <a className="sf-link" href="/products">
                  {t('insights', 'search.browseAll')}
                </a>
              </p>
            </div>
          ) : (
            <div
              className="sf-grid"
              style={{ '--sf-cols': columns, marginBlockStart: 'var(--t-space-xl)' } as CSSProperties}
            >
              {products.map((product, index) => (
                <ProductCard
                  key={product.id}
                  product={product}
                  template={context.template}
                  priority={index < columns}
                  cart={{ tenantId: context.tenantId, enabled: context.flags.cart }}
                />
              ))}
            </div>
          )}
        </div>
      </section>
    </StorefrontShell>
  );
}

/**
 * The merchant's own switch.
 *
 * Its own tiny read rather than a field on the cached storefront context, and the reason is the same
 * one `resolveAccess` gives for keeping entitlements out of the data cache: this decides whether a
 * route exists, and a five-minute-stale answer means a shop that turned search off keeps answering
 * search requests. One indexed read on a route nobody hits by accident.
 */
async function readSearchSwitch(tenantId: string): Promise<boolean> {
  const row = await tenantDb(tenantId, PUBLIC_ACTOR).site.findUnique({
    where: { tenantId },
    select: { searchEnabled: true },
  });
  return row?.searchEnabled === true;
}
