-- Phase 8 — cart, checkout settings and coupons.
--
-- Additive only, exactly as docs/PHASES.md rule 3 and this change's own rules require: every new
-- column on "orders" is nullable or safely defaulted, every new enum value is an ADD VALUE, and
-- nothing here alters the meaning of a single existing row. Every `buy_now` order from Phase 5
-- keeps its exact stored shape and exact behaviour — `channel` defaults it to `buy_now` for free,
-- and Phase 5's own status vocabulary (pending/paid/fulfilled/cancelled/refunded) is untouched.
--
-- The new feature keys `cart` and `coupons`, and the new `order_settings` capability, all default
-- OFF / plan-appropriate in prisma/seed.ts — not here. This migration only makes the SHAPES
-- possible; entitlements (src/server/entitlements) decide who ever sees them.
--
-- The DDL above the "-----" divider was generated by `prisma migrate diff` against this exact
-- schema (so it matches Prisma's own conventions byte for byte — no hand-transcription drift);
-- everything below it is hand-written, exactly as migration 0001 hand-wrote RLS and guards on
-- top of migration 0000's generated tables.

-- CreateEnum
CREATE TYPE "order_channel" AS ENUM ('buy_now', 'cart');

-- CreateEnum
CREATE TYPE "order_payment_method" AS ENUM ('cod', 'pickup', 'gateway');

-- CreateEnum
CREATE TYPE "coupon_type" AS ENUM ('percent', 'fixed', 'free_delivery');

-- CreateEnum
CREATE TYPE "coupon_scope" AS ENUM ('all', 'categories', 'products');

-- CreateEnum
CREATE TYPE "order_history_kind" AS ENUM ('created', 'status_changed', 'edited', 'note_added', 'cancelled');

-- AlterEnum
-- New capability (axis b). editable_by defaults to 'merchant' on every plan — see prisma/seed.ts
-- and the CapabilityKey enum's own comment in schema.prisma.
ALTER TYPE "capability_key" ADD VALUE 'order_settings';

-- AlterEnum
-- Two vocabularies, one Postgres enum, kept apart by the new orders.channel column below.
-- `buy_now` (Phase 5) keeps pending/paid/fulfilled/cancelled/refunded exactly as it always was;
-- `cart` (this phase) uses new/confirmed/preparing/delivered/cancelled. See the enum's own
-- comment in schema.prisma and src/server/orders/status.ts for the channel-aware state machine.
-- Every ADD VALUE here is safe inside this migration's transaction because no statement in this
-- same file uses any of these four new values as a literal (only IS NOT NULL / column
-- comparisons against `channel`, a different enum) — Postgres refuses to USE a value added
-- earlier in the same transaction, but adding several is fine.
ALTER TYPE "order_status" ADD VALUE 'new';
ALTER TYPE "order_status" ADD VALUE 'confirmed';
ALTER TYPE "order_status" ADD VALUE 'preparing';
ALTER TYPE "order_status" ADD VALUE 'delivered';

-- AlterTable
-- Every column is nullable or safely defaulted. Existing `buy_now` rows get channel='buy_now',
-- discount/delivery-fee=0, and NULL for everything else — a byte-for-byte no-op for Phase 5.
ALTER TABLE "orders" ADD COLUMN     "cancel_reason" TEXT,
ADD COLUMN     "cancelled_at" TIMESTAMP(3),
ADD COLUMN     "channel" "order_channel" NOT NULL DEFAULT 'buy_now',
ADD COLUMN     "coupon_id" TEXT,
ADD COLUMN     "delivery_address" TEXT,
ADD COLUMN     "delivery_area" TEXT,
ADD COLUMN     "delivery_fee_agorot" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "discount_agorot" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "edit_window_minutes" INTEGER,
ADD COLUMN     "payment_method" "order_payment_method",
ADD COLUMN     "subtotal_agorot" INTEGER,
ADD COLUMN     "tracking_code" TEXT;

-- CreateTable
CREATE TABLE "order_settings" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "edit_window_minutes" INTEGER NOT NULL DEFAULT 0,
    "delivery_fee_agorot" INTEGER NOT NULL DEFAULT 0,
    "free_delivery_over_agorot" INTEGER,
    "min_order_amount_agorot" INTEGER NOT NULL DEFAULT 0,
    "payment_methods" TEXT[] DEFAULT ARRAY['cod']::TEXT[],
    "delivery_areas" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "ordering_paused" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "order_settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "coupons" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "type" "coupon_type" NOT NULL,
    "value" INTEGER NOT NULL DEFAULT 0,
    "min_subtotal_agorot" INTEGER NOT NULL DEFAULT 0,
    "max_uses" INTEGER,
    "per_phone_limit" INTEGER,
    "starts_at" TIMESTAMP(3),
    "ends_at" TIMESTAMP(3),
    "active" BOOLEAN NOT NULL DEFAULT true,
    "scope" "coupon_scope" NOT NULL DEFAULT 'all',
    "scope_category_ids" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "scope_product_ids" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "uses_count" INTEGER NOT NULL DEFAULT 0,
    "created_by_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "coupons_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "coupon_redemptions" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "coupon_id" TEXT NOT NULL,
    "order_id" TEXT NOT NULL,
    "customer_phone" TEXT NOT NULL,
    "discount_agorot" INTEGER NOT NULL,
    "redeemed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "coupon_redemptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_history_entries" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "order_id" TEXT NOT NULL,
    "kind" "order_history_kind" NOT NULL,
    "actor_role" TEXT NOT NULL,
    "actor_user_id" TEXT,
    "note" TEXT,
    "before" JSONB,
    "after" JSONB,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "order_history_entries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- GLOBAL (prisma/GLOBAL_TABLES.md) and a singleton by construction — see the CHECK constraint in
-- section 3 below and the model's own comment in schema.prisma.
CREATE TABLE "platform_settings" (
    "id" TEXT NOT NULL DEFAULT 'singleton',
    "order_edit_window_max_minutes" INTEGER NOT NULL DEFAULT 60,
    "updated_by_id" TEXT,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "platform_settings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "order_settings_tenant_id_key" ON "order_settings"("tenant_id");

-- CreateIndex
CREATE INDEX "order_settings_tenant_id_idx" ON "order_settings"("tenant_id");

-- CreateIndex
CREATE INDEX "coupons_tenant_id_active_idx" ON "coupons"("tenant_id", "active");

-- CreateIndex
CREATE UNIQUE INDEX "coupons_tenant_id_code_key" ON "coupons"("tenant_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "coupon_redemptions_order_id_key" ON "coupon_redemptions"("order_id");

-- CreateIndex
CREATE INDEX "coupon_redemptions_tenant_id_coupon_id_idx" ON "coupon_redemptions"("tenant_id", "coupon_id");

-- CreateIndex
CREATE INDEX "coupon_redemptions_tenant_id_customer_phone_idx" ON "coupon_redemptions"("tenant_id", "customer_phone");

-- CreateIndex
CREATE INDEX "order_history_entries_tenant_id_order_id_created_at_idx" ON "order_history_entries"("tenant_id", "order_id", "created_at");

-- CreateIndex
CREATE INDEX "orders_tenant_id_channel_status_placed_at_idx" ON "orders"("tenant_id", "channel", "status", "placed_at");

-- CreateIndex
CREATE UNIQUE INDEX "orders_tenant_id_tracking_code_key" ON "orders"("tenant_id", "tracking_code");

-- AddForeignKey
ALTER TABLE "orders" ADD CONSTRAINT "orders_coupon_id_fkey" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_settings" ADD CONSTRAINT "order_settings_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "coupons" ADD CONSTRAINT "coupons_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "coupon_redemptions_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "coupon_redemptions_coupon_id_fkey" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "coupon_redemptions_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_history_entries" ADD CONSTRAINT "order_history_entries_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_history_entries" ADD CONSTRAINT "order_history_entries_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- =============================================================================
-- Hand-written from here on — nothing below this line came from `prisma migrate diff`.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Row-level security on the four new tenant-owned tables — the exact generic template from
--    prisma/migrations/20260809000100_rls_roles_and_guards/migration.sql, scoped to just these,
--    because that migration's own DO block already ran for every table that existed before it.
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  t text;
  tenant_tables text[] := ARRAY[
    'order_settings',
    'coupons',
    'coupon_redemptions',
    'order_history_entries'
  ];
BEGIN
  FOREACH t IN ARRAY tenant_tables LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);

    -- The generic template. Identical USING and WITH CHECK: a tenant may not read another
    -- tenant's row, and may not write one either.
    EXECUTE format($p$
      CREATE POLICY tenant_isolation ON %I
        FOR ALL TO app_web
        USING (
          tenant_id = current_setting('app.tenant_id', true)
          OR current_setting('app.actor_role', true) = 'super_admin'
        )
        WITH CHECK (
          tenant_id = current_setting('app.tenant_id', true)
          OR current_setting('app.actor_role', true) = 'super_admin'
        )
    $p$, t);

    -- app_system reads ids to fan out. It never writes a tenant-owned table — enforced by the
    -- GRANTs below, not merely by this policy.
    EXECUTE format($p$
      CREATE POLICY system_read ON %I FOR SELECT TO app_system USING (true)
    $p$, t);

    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO app_web', t);
    EXECUTE format('GRANT SELECT ON %I TO app_system', t);
  END LOOP;
END
$$;

-- -----------------------------------------------------------------------------
-- 2. platform_settings — GLOBAL, no RLS, matching "plans" / "plan_features" (migration 0001):
--    readable by every web request, writable by app_web (the super-admin-only route is the
--    actual enforcement — src/server/platform-settings.ts), read-only for app_system.
-- -----------------------------------------------------------------------------
GRANT SELECT ON "platform_settings" TO app_web, app_system;
GRANT INSERT, UPDATE ON "platform_settings" TO app_web;

-- -----------------------------------------------------------------------------
-- 3. Database-level guards that do not depend on application code being correct — the same
--    philosophy as migration 0001's section 2.
-- -----------------------------------------------------------------------------

-- Only one platform_settings row can ever exist: the primary key already forces at most one row
-- with id='singleton', and this CHECK makes any OTHER id unrepresentable, so "a second row with
-- a different id" is not a bug application code could introduce even by accident.
ALTER TABLE "platform_settings" ADD CONSTRAINT "platform_settings_is_singleton"
  CHECK ("id" = 'singleton');

ALTER TABLE "platform_settings" ADD CONSTRAINT "platform_settings_cap_nonneg"
  CHECK ("order_edit_window_max_minutes" >= 0);

-- Money is agorot, and agorot are not negative — the same rule migration 0001 already applies to
-- products, payments, plans and order_items.
ALTER TABLE "order_settings" ADD CONSTRAINT "order_settings_amounts_nonneg" CHECK (
  "edit_window_minutes" >= 0
  AND "delivery_fee_agorot" >= 0
  AND "min_order_amount_agorot" >= 0
  AND ("free_delivery_over_agorot" IS NULL OR "free_delivery_over_agorot" >= 0)
);

ALTER TABLE "coupons" ADD CONSTRAINT "coupons_amounts_nonneg" CHECK (
  "value" >= 0 AND "min_subtotal_agorot" >= 0
);

-- The redemption counter must never exceed the cap it exists to enforce — the backstop for
-- `redeemCouponInTx`'s atomic conditional UPDATE (src/server/orders/coupons.ts), not a
-- substitute for it: this catches a BUG in that discipline, it does not replace the
-- concurrency-safety the conditional UPDATE itself provides.
ALTER TABLE "coupons" ADD CONSTRAINT "coupons_uses_within_max" CHECK (
  "max_uses" IS NULL OR "uses_count" <= "max_uses"
);

-- Coupon codes are always stored uppercase (src/server/orders/schema.ts normalises on write);
-- this is the guard that holds even if a future write path forgets.
ALTER TABLE "coupons" ADD CONSTRAINT "coupons_code_uppercase" CHECK ("code" = upper("code"));

ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "coupon_redemptions_discount_nonneg" CHECK (
  "discount_agorot" >= 0
);

-- A cart-channel order always carries its cart-specific fields; a buy_now order never needs
-- them. This is what stops a code path from writing a cart order with no tracking code, no
-- snapshot payment method and no subtotal — exactly the fields self-service tracking and the
-- totals breakdown depend on.
ALTER TABLE "orders" ADD CONSTRAINT "orders_cart_fields_coherent" CHECK (
  "channel" <> 'cart'
  OR ("subtotal_agorot" IS NOT NULL AND "tracking_code" IS NOT NULL AND "payment_method" IS NOT NULL)
);

ALTER TABLE "orders" ADD CONSTRAINT "orders_cart_amounts_nonneg" CHECK (
  "discount_agorot" >= 0
  AND "delivery_fee_agorot" >= 0
  AND ("subtotal_agorot" IS NULL OR "subtotal_agorot" >= 0)
);

-- Seed the singleton row HERE, not only in prisma/seed.ts: a merchant dashboard that reads
-- order_edit_window_max_minutes before the next `pnpm db:seed` run must never see "no row" as
-- the reason a cap silently failed to apply. `pnpm db:seed` is idempotent against it (ON CONFLICT
-- DO NOTHING here means seed.ts's own upsert is what actually applies an operator-configured
-- value later).
INSERT INTO "platform_settings" ("id", "order_edit_window_max_minutes", "updated_at")
VALUES ('singleton', 60, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
