import { dispatchJob } from '@/server/billing';
import { randomToken } from '@/server/crypto';
import type { TenantTx } from '@/server/db';
import { logger } from '@/server/logger';
import { tenantJob } from '@/server/queues';
import {
  MEDIA_QUEUE,
  MediaError,
  PROCESS_UPLOAD_JOB,
  admitUpload,
  adjustTenantStorageBytes,
  assertProductImageAlt,
  mediaSourceKey,
  mediaStorage,
  readTenantStorageBytes,
  resolveStorageLimits,
  sniffIngestible,
} from '@/server/media';
import { svgPlaceholder } from './placeholder';
import { findSeedAsset } from './seed-assets';
import type { DemoProduct, PackKey } from './types';

/**
 * Product images for a demo, written INSIDE the demo's own transaction.
 *
 * WHY NOT `ingestInternalImage()`. It is A3's door for platform-generated bytes and it does
 * everything this file does — but it opens its OWN `withTenantTxn` and enqueues the processing job
 * before returning. Called from inside `buildDemoContent`, which already runs inside the
 * transaction `createDemo` opened, that would take a second connection per product, commit fifteen
 * `Media` rows independently of the catalogue they belong to, and fire fifteen jobs before the
 * catalogue exists. `DemoContentResult.afterCommit` exists precisely because the enqueue must wait
 * for the commit (`src/server/billing/demo-content.ts`), so the pieces are assembled here from the
 * same A3 primitives instead: same magic-byte sniff, same key layout, same quota accounting, same
 * queue and same processor. A demo's images end up indistinguishable from an uploaded one — which
 * is what makes the library, the purge and the orphan sweep understand them.
 *
 * WHY THE BYTES GO TO STORAGE BEFORE THE ROW. Same order as the upload path: an object with no row
 * is a known, sweepable state; a row with no object is a broken tile on a shareable link. If the
 * build fails afterwards, `discardObjects()` takes them back immediately rather than leaving them
 * to A3's orphan sweep — which is a backstop, not a cleanup strategy.
 */

export interface DemoImage {
  mediaId: string;
  /** Normalised, Arabic, non-empty — `ProductImage.alt` is NOT NULL by design (invariant 4). */
  alt: string;
}

export interface DemoImageWriter {
  write(product: DemoProduct): Promise<DemoImage>;
  /** One quota update for the whole catalogue, applied before the transaction returns. */
  commitUsage(): Promise<void>;
  mediaIds(): string[];
  /** Enqueue variant processing — called by `createDemo` AFTER the commit, never inside it. */
  enqueueProcessing(): Promise<void>;
  /** Best-effort undo of the bytes written so far, for a build that failed. */
  discardObjects(): Promise<void>;
}

interface WrittenObject {
  mediaId: string;
  key: string;
}

export async function createDemoImageWriter(
  tx: TenantTx,
  tenantId: string,
  packKey: PackKey,
): Promise<DemoImageWriter> {
  const limits = await resolveStorageLimits(tenantId);
  if (!limits) {
    // A demo sits on the hidden `demo` plan, which carries both keys. Missing means the plan was
    // seeded wrong, and writing bytes on that basis is how a limit gets quietly bypassed.
    throw new MediaError('limitsUnavailable');
  }

  /**
   * ONE locked read for the whole catalogue, not one per image.
   *
   * `readTenantStorageBytes` is `SELECT … FOR UPDATE` on the tenant row. Fifteen of them inside one
   * transaction would re-take a lock this transaction already holds — pointless work — and fifteen
   * separate `adjustTenantStorageBytes` statements would each rewrite the same column. The running
   * total below serves the same admission purpose: every image is checked against the quota
   * including the ones already written in this build.
   */
  const startingBytes = await readTenantStorageBytes(tx, tenantId);

  const written: WrittenObject[] = [];
  let addedBytes = 0;

  return {
    async write(product: DemoProduct): Promise<DemoImage> {
      const alt = assertProductImageAlt(product.imageAlt);
      const { bytes, fileName } = await imageBytesFor(packKey, product);

      const sniffed = sniffIngestible(bytes);
      if (!sniffed.ok) {
        // Reachable only through a corrupt seed photo: the generated SVG is ours.
        throw new MediaError(sniffed.reason === 'empty' ? 'emptyFile' : 'unsupportedType');
      }

      const sizeBytes = bytes.byteLength;
      admitUpload({ limits, usedBytes: startingBytes + addedBytes, fileSizeBytes: sizeBytes });

      const mediaId = randomToken(12);
      const key = mediaSourceKey(tenantId, mediaId, sniffed.mimeType);

      await mediaStorage().put(key, bytes, { contentType: sniffed.mimeType });
      written.push({ mediaId, key });

      await tx.media.create({
        data: {
          id: mediaId,
          tenantId,
          key,
          originalName: fileName,
          mimeType: sniffed.mimeType,
          sizeBytes,
          // The product's own Arabic alt, carried through as-is (A3 policy). It lands on the
          // `Media` row as well as on `ProductImage` so the library screen shows it too.
          altText: alt,
          status: 'pending',
          createdById: null,
        },
      });

      addedBytes += sizeBytes;
      return { mediaId, alt };
    },

    async commitUsage(): Promise<void> {
      await adjustTenantStorageBytes(tx, tenantId, addedBytes);
    },

    mediaIds(): string[] {
      return written.map((item) => item.mediaId);
    },

    /**
     * BEST EFFORT, AND BOUNDED — because by the time this runs the demo has already committed.
     *
     * `createDemo` awaits `afterCommit()` inside the same `try` whose `catch` calls
     * `discardHalfBuiltDemo()`. So an exception here does not fail an enqueue: it DELETES a
     * complete, correct demo and its owner. And a raw `enqueue()` is exactly the throw that would
     * do it — `queueRedis()` is configured with `maxRetriesPerRequest: null` (BullMQ blocks on
     * BRPOPLPUSH and a retry limit would tear the worker down mid-wait), so a command against a
     * dead Redis never settles at all and the operator gets a spinner instead of a shop.
     *
     * `dispatchJob` is the machinery Phase 1 built for precisely this shape and states the rule in
     * its own comment: "the enqueue is never load-bearing for a committed transition". It races a
     * timer, swallows the failure, logs it, and reports whether the job was accepted.
     *
     * WHAT A DROPPED JOB COSTS: the `Media` row stays `pending`, so the product renders A2's
     * placeholder letter instead of a photograph. The shop, the catalogue and the link are all
     * correct. The demo detail screen shows the pending count, so an operator can see it before
     * sending the link, and A3's orphan sweep is the backstop for rows that never process.
     */
    async enqueueProcessing(): Promise<void> {
      let dropped = 0;

      for (const { mediaId } of written) {
        const scheduled = await dispatchJob(
          MEDIA_QUEUE,
          tenantJob(tenantId, PROCESS_UPLOAD_JOB, { mediaId }),
        );
        if (!scheduled) dropped += 1;
      }

      if (dropped > 0) {
        logger().error(
          { tenantId, dropped, total: written.length },
          'demo images could not be queued for processing — the demo is intact but unillustrated',
        );
      }
    },

    async discardObjects(): Promise<void> {
      for (const { key } of written) {
        await mediaStorage()
          .delete(key)
          .catch((error: unknown) => {
            logger().error(
              { tenantId, key, error: (error as Error).message },
              'a discarded demo image could not be removed — the orphan sweep will collect it',
            );
          });
      }
    },
  };
}

/**
 * A real photo when one exists, the generated placeholder otherwise (the pack contract, step 3).
 *
 * No external URL is ever consulted. The SVG is produced here and a millisecond later handed to the
 * same pipeline as an uploaded file — which is the only reason A3 accepts a vector at all
 * (`ingestInternalImage`'s comment): the bytes did not come from outside.
 */
async function imageBytesFor(
  packKey: PackKey,
  product: DemoProduct,
): Promise<{ bytes: Buffer; fileName: string }> {
  const seeded = await findSeedAsset(packKey, product.sku);
  if (seeded) return { bytes: seeded.bytes, fileName: seeded.fileName };

  const svg = svgPlaceholder(packKey, product.name, product.sku);
  return { bytes: Buffer.from(svg, 'utf8'), fileName: `${product.sku}.svg` };
}
