import { st } from '../i18n';
import { legalHref, legalPagesFor } from '../lib/legal';
import { SECTION_ANCHORS } from '../section-anchors';
import type { StorefrontContext } from '../view-model';
import { SocialLinks } from './social-links';

/**
 * The footer, including the PERMANENT legal strip.
 *
 * The legal links are not content a merchant can delete: CLAUDE.md's compliance defaults put a
 * privacy policy, terms, a business identity page and an accessibility statement on every site
 * on every plan, and add the returns policy plus the permanent "إلغاء معاملة" link the moment
 * selling is enabled. They are generated by `src/server/legal` in Phase 6 as ordinary Page
 * rows; the LIST lives in `lib/legal.ts` so Phase 6 never has to open a template file.
 *
 * The social column is only rendered when there is something in it. Every demo tenant has zero
 * social links and so does every new account, so the empty case is the COMMON case — which is
 * why the contact column carries the weight and the follow column simply does not appear,
 * rather than leaving a heading floating over blank space.
 */
export function SiteFooter({ context }: { context: StorefrontContext }) {
  const { site, socialLinks } = context;
  const legal = legalPagesFor(site.sellingEnabled);
  const year = new Date().getFullYear();

  return (
    <footer className="sf-footer" aria-label={st('footer.label')}>
      <div className="sf-shell sf-footer__inner">
        <div>
          <h2>{site.name}</h2>
          {site.tagline ? <p className="sf-block__lead">{site.tagline}</p> : null}
        </div>

        <div>
          <h2>{st('footer.links')}</h2>
          <ul>
            <li>
              <a href="/">{st('nav.home')}</a>
            </li>
            <li>
              <a href="/products">{st('nav.products')}</a>
            </li>
            <li>
              <a href={`/#${SECTION_ANCHORS.contact_whatsapp}`}>{st('nav.contact')}</a>
            </li>
          </ul>
        </div>

        <div>
          <h2>{st('footer.contact')}</h2>
          <ul>
            {site.phone ? (
              <li>
                <a href={`tel:${site.phone.replace(/\s/g, '')}`}>{site.phone}</a>
              </li>
            ) : null}
            {site.address ? <li>{site.address}</li> : null}
            {site.hours ? <li>{site.hours}</li> : null}
            {site.email ? (
              <li>
                <a href={`mailto:${site.email}`}>{site.email}</a>
              </li>
            ) : null}
          </ul>
        </div>

        {socialLinks.length > 0 ? (
          <div>
            <h2>{st('social.title')}</h2>
            <SocialLinks links={socialLinks} />
          </div>
        ) : null}
      </div>

      <div className="sf-shell">
        <nav className="sf-legal" aria-label={st('legal.label')}>
          {legal.map((page) => (
            <a key={page.slug} href={legalHref(page.slug)}>
              {st(`legal.${page.labelKey}`)}
            </a>
          ))}
          <span>{st('footer.rights', { year: String(year), name: site.name })}</span>
        </nav>
      </div>
    </footer>
  );
}
