import { st } from '../i18n';
import { isolateRanges } from '../lib/ltr-ranges';
import { hasContactSection } from '../lib/arrangement';
import { resolveHoursLine } from '../lib/hours-summary';
import { legalHref, legalPagesFor } from '../lib/legal';
import { SECTION_ANCHORS } from '../section-anchors';
import type { StorefrontContext } from '../view-model';
import { PushToggle } from './push-toggle';
import { SocialLinks } from './social-links';

/**
 * The footer, including the PERMANENT legal strip.
 *
 * The legal links are not content a merchant can delete: CLAUDE.md's compliance defaults put a
 * privacy policy, terms, a business identity page and an accessibility statement on every site
 * on every plan, and add the returns policy plus the permanent "إلغاء معاملة" link the moment
 * selling is enabled. They are generated by `src/server/legal` in Phase 6 as ordinary Page
 * rows; the LIST lives in `lib/legal.ts` so Phase 6 never has to open a template file.
 *
 * The social column is only rendered when there is something in it. Every demo tenant has zero
 * social links and so does every new account, so the empty case is the COMMON case — which is
 * why the contact column carries the weight and the follow column simply does not appear,
 * rather than leaving a heading floating over blank space.
 */
export function SiteFooter({
  context,
  showPush = false,
}: {
  context: StorefrontContext;
  /**
   * Decided by the shell, because it is the only component that knows whether the consent banner
   * is currently on screen — and the push offer waits for that to be answered (Phase 4).
   */
  showPush?: boolean;
}) {
  const { site, socialLinks } = context;
  const legal = legalPagesFor(site.sellingEnabled);
  const year = new Date().getFullYear();

  /**
   * The structured week first, the free-text box second — see `lib/hours-summary.ts` and the same
   * change in `sections/contact-whatsapp.tsx`. `hasContactDetails` asks about the RESOLVED line
   * rather than about `site.hours`, or a shop that filled in the picker and left the textarea empty
   * would have its hours dropped from the "is there anything in this column" test and then rendered
   * inside it — which is how a column ends up one item shorter than the condition that showed it.
   */
  const hoursLine = resolveHoursLine(context.openingHours, site.hours);
  const hasContactDetails = Boolean(site.phone || site.address || hoursLine || site.email);

  return (
    <footer className="sf-footer" aria-label={st('footer.label')}>
      <div className="sf-shell sf-footer__inner">
        <div>
          <h2>{site.name}</h2>
          {site.tagline ? <p className="sf-block__lead">{site.tagline}</p> : null}
        </div>

        <div>
          <h2>{st('footer.links')}</h2>
          <ul>
            <li>
              <a href="/">{st('nav.home')}</a>
            </li>
            <li>
              <a href="/products">{st('nav.products')}</a>
            </li>
            {/* Only when the home arrangement has the section — see lib/arrangement.ts. */}
            {hasContactSection(context) ? (
              <li>
                <a href={`/#${SECTION_ANCHORS.contact_whatsapp}`}>{st('nav.contact')}</a>
              </li>
            ) : null}
          </ul>
        </div>

        {/*
          The heading is conditional on there being something under it — the same rule the social
          column already followed one block down, and it has to be, because all four of these
          fields are optional. An account A1 opens with a name and a template has none of them, so
          the merchant's first look at their own site was a "معلومات التواصل" heading announcing
          an empty list. That is precisely the failure `SocialLinks` was written to avoid, sitting
          in the same file.
        */}
        {hasContactDetails ? (
          <div>
            <h2>{st('footer.contact')}</h2>
            <ul>
              {site.phone ? (
                <li>
                  <a href={`tel:${site.phone.replace(/\s/g, '')}`}>{site.phone}</a>
                </li>
              ) : null}
              {site.address ? <li>{site.address}</li> : null}
              {hoursLine ? <li className="sf-footer__hours">{isolateRanges(hoursLine)}</li> : null}
              {site.email ? (
                <li>
                  <a href={`mailto:${site.email}`}>{site.email}</a>
                </li>
              ) : null}
            </ul>
          </div>
        ) : null}

        {/*
          THE ONLY SOCIAL ROW ON THE SITE (2026-09-06, owner-directed). `contact-whatsapp.tsx` used
          to render a second identical one a few hundred pixels above this; it no longer does.

          It gets its own FULL-WIDTH band rather than a 15rem grid column, and that is what fixes the
          «طولي» complaint: eight 44px circles cannot fit in one auto-fit track, so they wrapped into
          a two-per-row stack that read as a vertical list. Spanning every column gives one row, and
          `.sf-footer__social` centres it under the columns instead of leaving it ragged at one end.
        */}
        {socialLinks.length > 0 ? (
          <div className="sf-footer__social">
            <h2>{st('social.title')}</h2>
            <SocialLinks links={socialLinks} />
          </div>
        ) : null}

        {/*
          Push lives here rather than in a pinned bar: a permission request has to be tied to a
          user gesture to work reliably at all, and the UNSUBSCRIBE has to be findable on every
          page forever — not only in the moment a prompt happened to appear. Labels are resolved
          here because the control is a client component and must not import the i18n layer.
        */}
        {showPush && context.pushPublicKey ? (
          <PushToggle
            publicKey={context.pushPublicKey}
            labels={{
              heading: st('push.heading'),
              hint: st('push.hint'),
              subscribe: st('push.subscribe'),
              unsubscribe: st('push.unsubscribe'),
              working: st('push.working'),
              subscribed: st('push.subscribed'),
              denied: st('push.denied'),
              failed: st('push.failed'),
            }}
          />
        ) : null}
      </div>

      <div className="sf-shell">
        <nav className="sf-legal" aria-label={st('legal.label')}>
          {legal.map((page) => (
            <a key={page.slug} href={legalHref(page.slug)}>
              {st(`legal.${page.labelKey}`)}
            </a>
          ))}
          <span>{st('footer.rights', { year: String(year), name: site.name })}</span>
        </nav>

        {/*
          The agency credit (2026-08-21, owner-directed). PLATFORM state, not the merchant's: the
          toggle, the name and the link live on the settings singleton, edited from the admin panel
          only — no dashboard surface, no capability, nothing a merchant can switch. `context.credit`
          is null whenever the owner has it off, and null renders NOTHING: no bar, no empty strip.

          Styled entirely through tokens (`.sf-credit` in storefront.css), so the line takes each
          template's own muted text and link colours — which are the two tokens `deriveColorTokens`
          already guards to AA against every surface they can land on. That is what "matches the
          site's colours" means here without a single per-tenant setting.
        */}
        {context.credit ? (
          <p className="sf-credit">
            {st('footer.credit')}{' '}
            {/* The class is load-bearing: the shell's `.sf-root a:not([class])` forces unclassed
                links to inherit, at a specificity `.sf-credit a` cannot beat — so an unclassed
                anchor here rendered muted instead of in `--t-link`. Classing it is that rule's
                own designed escape hatch, not a workaround. */}
            <a
              className="sf-credit__link"
              href={context.credit.url}
              target="_blank"
              rel="noreferrer noopener"
            >
              {context.credit.name}
            </a>
          </p>
        ) : null}
      </div>
    </footer>
  );
}
