/**
 * The media pipeline's own vocabulary.
 *
 * These mirror the Prisma enums (`MediaStatus`, `MediaVariantKind`, `ImageFormat`) as plain
 * string unions so that callers outside `src/server/db` — the upload route, B2's library screen,
 * B3's demo generator — can name a variant without importing the generated client, which
 * invariant 1 forbids them from doing.
 */

export const MEDIA_VARIANT_KINDS = ['thumb', 'card', 'full'] as const;
export type MediaVariantKind = (typeof MEDIA_VARIANT_KINDS)[number];

export const MEDIA_VARIANT_FORMATS = ['webp', 'avif'] as const;
export type ImageFormat = (typeof MEDIA_VARIANT_FORMATS)[number];

export type MediaStatus = 'pending' | 'processing' | 'ready' | 'failed';

/** thumb 400 / card 800 / full 1600 (invariant 4). Never upscaled past the original. */
export const VARIANT_WIDTHS: Record<MediaVariantKind, number> = {
  thumb: 400,
  card: 800,
  full: 1600,
};

/**
 * What the merchant may upload, decided by BYTES and nothing else.
 *
 * Uploaded SVG is never on this list: an SVG is a script container, and one served from the
 * media CDN would run on a storefront's origin. B3's placeholders are SVG, but they are
 * generated by the platform and enter through `ingestInternalImage`, never through the endpoint.
 */
export const UPLOADABLE_IMAGE_MIMES = ['image/jpeg', 'image/png', 'image/webp'] as const;
export type UploadableImageMime = (typeof UPLOADABLE_IMAGE_MIMES)[number];

/** Everything the pipeline can rasterise, including platform-generated vector sources. */
export type IngestibleMime = UploadableImageMime | 'image/svg+xml';

export interface MediaVariantView {
  kind: MediaVariantKind;
  format: ImageFormat;
  width: number;
  height: number;
  sizeBytes: number;
  key: string;
  /** Always a CDN URL. Never the app server's disk in production (invariant 4). */
  url: string;
}

export interface MediaView {
  id: string;
  status: MediaStatus;
  mimeType: string;
  originalName: string | null;
  altText: string | null;
  width: number | null;
  height: number | null;
  sizeBytes: number;
  createdAt: Date;
  /** The Arabic sentence to show for a failed item. Null while the item is healthy. */
  failureMessage: string | null;
  /** The card-sized WebP, or null while the item is not ready. */
  previewUrl: string | null;
  variants: MediaVariantView[];
}

export interface StorageUsageView {
  usedBytes: number;
  limitBytes: number;
  remainingBytes: number;
  /** 0-100, clamped. The dashboard meter reads this. */
  percentUsed: number;
  /** Pre-formatted Arabic, e.g. "استعملت 120 ميغابايت من 3 غيغابايت". */
  label: string;
  usedLabel: string;
  limitLabel: string;
}
