-- Phase 9 — merchant depth: catalogue variants and stock, homepage content, delivery zones and
-- carriers, tax settings, a customers index, and first-party visitor analytics.
--
-- ADDITIVE ONLY, and the bar is the one Phase 8 set: every new column on an existing table is
-- nullable or safely defaulted, every new enum value is an ADD VALUE, and no statement here
-- changes the meaning of a single stored row.
--
-- Three specific promises this migration keeps:
--
--   * `order_settings.zone_pricing_enabled` defaults to FALSE, so every tenant that exists today
--     keeps Phase 8's flat `delivery_fee_agorot` behaviour byte for byte. Zone pricing is opt-in
--     per tenant, and there is never a moment where two pricing systems both half-apply.
--   * `products.stock_policy` defaults to `untracked`, so no existing product suddenly becomes
--     unsellable because its `stock_qty` defaulted to 0.
--   * `products.variants Json?` is NOT dropped. Q19 moved variants to a relational table; the
--     column is dead but dropping it would cost a migration for no benefit. See its docblock.
--
-- `demo_requests.purge_after` is deliberately NOT touched. `prisma migrate diff` wants to DROP its
-- DEFAULT, because migration 0001 set `now() + interval '30 days'` in raw SQL and the Prisma schema
-- has no way to express it. That is known, intended drift; executing the diff's suggestion would
-- silently break the demo-request retention promise.
--
-- The DDL above the divider was generated by `prisma migrate diff` against this exact schema, so
-- it matches Prisma's own conventions with no hand-transcription drift. Everything below the
-- divider is hand-written, exactly as migrations 0001 and 0004 hand-wrote RLS and guards on top of
-- generated tables.

-- CreateEnum
CREATE TYPE "strip_color" AS ENUM ('dark', 'primary', 'secondary', 'light');

-- CreateEnum
CREATE TYPE "analytics_event_kind" AS ENUM ('page_view', 'section_view', 'product_view', 'search', 'whatsapp_click', 'add_to_cart', 'checkout_start', 'order_placed');

-- CreateEnum
CREATE TYPE "stock_policy" AS ENUM ('untracked', 'track_and_block', 'track_and_allow');

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "capability_key" ADD VALUE 'banners';
ALTER TYPE "capability_key" ADD VALUE 'opening_hours';
ALTER TYPE "capability_key" ADD VALUE 'trust_badges';
ALTER TYPE "capability_key" ADD VALUE 'store_stats';
ALTER TYPE "capability_key" ADD VALUE 'delivery_zones';
ALTER TYPE "capability_key" ADD VALUE 'size_guide';
ALTER TYPE "capability_key" ADD VALUE 'tax_settings';
ALTER TYPE "capability_key" ADD VALUE 'logo';

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "section_type" ADD VALUE 'banner_slider';
ALTER TYPE "section_type" ADD VALUE 'trust_badges';
ALTER TYPE "section_type" ADD VALUE 'opening_hours';
ALTER TYPE "section_type" ADD VALUE 'store_stats';
ALTER TYPE "section_type" ADD VALUE 'new_arrivals';
ALTER TYPE "section_type" ADD VALUE 'best_sellers';
ALTER TYPE "section_type" ADD VALUE 'related_products';
ALTER TYPE "section_type" ADD VALUE 'search_bar';

-- AlterTable
ALTER TABLE "order_items" ADD COLUMN     "variant_id" TEXT,
ADD COLUMN     "variant_label" TEXT;

-- AlterTable
ALTER TABLE "order_settings" ADD COLUMN     "cod_fee_agorot" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "cod_max_agorot" INTEGER,
ADD COLUMN     "unlisted_town_fee_agorot" INTEGER,
ADD COLUMN     "zone_pricing_enabled" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "platform_settings" ADD COLUMN     "analytics_max_dwell_ms" INTEGER NOT NULL DEFAULT 120000,
ADD COLUMN     "analytics_raw_retention_days" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "low_stock_threshold_default" INTEGER NOT NULL DEFAULT 3;

-- AlterTable
ALTER TABLE "products" ADD COLUMN     "archived_at" TIMESTAMP(3),
ADD COLUMN     "care_instructions" TEXT,
ADD COLUMN     "compare_at_price_agorot" INTEGER,
ADD COLUMN     "low_stock_threshold" INTEGER,
ADD COLUMN     "stock_policy" "stock_policy" NOT NULL DEFAULT 'untracked',
ADD COLUMN     "stock_qty" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "tags" TEXT[] DEFAULT ARRAY[]::TEXT[];

-- AlterTable
ALTER TABLE "sites" ADD COLUMN     "announcement_bar_color" "strip_color" NOT NULL DEFAULT 'dark',
ADD COLUMN     "home_strip_color" "strip_color" NOT NULL DEFAULT 'primary',
ADD COLUMN     "home_strip_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "home_strip_ends_at" TIMESTAMP(3),
ADD COLUMN     "home_strip_link" TEXT,
ADD COLUMN     "home_strip_starts_at" TIMESTAMP(3),
ADD COLUMN     "home_strip_text" TEXT,
ADD COLUMN     "hours_note" TEXT,
ADD COLUMN     "search_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "size_guide_columns" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "size_guide_note" TEXT;

-- CreateTable
CREATE TABLE "banners" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "image_media_id" TEXT,
    "alt" TEXT,
    "title" TEXT NOT NULL,
    "subtitle" TEXT,
    "cta_label" TEXT,
    "cta_href" TEXT,
    "sort" INTEGER NOT NULL DEFAULT 0,
    "published" BOOLEAN NOT NULL DEFAULT false,
    "starts_at" TIMESTAMP(3),
    "ends_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "banners_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "trust_badges" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "icon" TEXT NOT NULL DEFAULT 'check',
    "title" TEXT NOT NULL,
    "subtitle" TEXT,
    "sort" INTEGER NOT NULL DEFAULT 0,
    "published" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "trust_badges_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "opening_hours" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "weekday" INTEGER NOT NULL,
    "closed" BOOLEAN NOT NULL DEFAULT false,
    "opens_at" TEXT,
    "closes_at" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "opening_hours_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "store_stats" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "sort" INTEGER NOT NULL DEFAULT 0,
    "published" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "store_stats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_variants" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "product_id" TEXT NOT NULL,
    "size" TEXT NOT NULL DEFAULT '',
    "colour" TEXT NOT NULL DEFAULT '',
    "sku" TEXT,
    "price_agorot_override" INTEGER,
    "stock_qty" INTEGER NOT NULL DEFAULT 0,
    "available" BOOLEAN NOT NULL DEFAULT true,
    "sort" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "product_variants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "size_guide_entries" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "category_id" TEXT,
    "label" TEXT NOT NULL,
    "cells" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "sort" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "size_guide_entries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "carriers" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "phone" TEXT,
    "website" TEXT,
    "notes" TEXT,
    "hidden" BOOLEAN NOT NULL DEFAULT false,
    "sort" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "carriers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "carrier_rates" (
    "id" TEXT NOT NULL,
    "carrier_id" TEXT NOT NULL,
    "zone_name" TEXT NOT NULL,
    "fee_agorot" INTEGER NOT NULL,
    "eta_label" TEXT,
    "towns" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "sort" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "carrier_rates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tenant_carriers" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "carrier_id" TEXT NOT NULL,
    "reference" TEXT,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "sort" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "tenant_carriers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "delivery_zones" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "fee_agorot" INTEGER NOT NULL,
    "eta_label" TEXT,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "sort" INTEGER NOT NULL DEFAULT 0,
    "seeded_from_carrier_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "delivery_zones_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "delivery_zone_towns" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "zone_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "normalised" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "delivery_zone_towns_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tax_settings" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "business_number" TEXT,
    "legal_name" TEXT,
    "vat_rate_basis_points" INTEGER,
    "prices_include_vat" BOOLEAN NOT NULL DEFAULT true,
    "invoice_provider" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "tax_settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "customers" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "name" TEXT,
    "area" TEXT,
    "orders_count" INTEGER NOT NULL DEFAULT 0,
    "total_spent_agorot" INTEGER NOT NULL DEFAULT 0,
    "first_order_at" TIMESTAMP(3),
    "last_order_at" TIMESTAMP(3),
    "marketing_consent" BOOLEAN NOT NULL DEFAULT false,
    "marketing_consent_at" TIMESTAMP(3),
    "notes" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "customers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "analytics_events" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "kind" "analytics_event_kind" NOT NULL,
    "path" TEXT NOT NULL,
    "target" TEXT,
    "dwell_ms" INTEGER,
    "search_term" TEXT,
    "result_count" INTEGER,
    "visitor_key" TEXT NOT NULL,
    "device_kind" TEXT,
    "occurred_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "analytics_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "analytics_daily" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "day" DATE NOT NULL,
    "path" TEXT NOT NULL,
    "visitors" INTEGER NOT NULL DEFAULT 0,
    "pageviews" INTEGER NOT NULL DEFAULT 0,
    "product_views" INTEGER NOT NULL DEFAULT 0,
    "whatsapp_clicks" INTEGER NOT NULL DEFAULT 0,
    "add_to_carts" INTEGER NOT NULL DEFAULT 0,
    "checkout_starts" INTEGER NOT NULL DEFAULT 0,
    "orders" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "analytics_daily_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "section_dwell_daily" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "day" DATE NOT NULL,
    "section" TEXT NOT NULL,
    "views" INTEGER NOT NULL DEFAULT 0,
    "total_dwell_ms" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "section_dwell_daily_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "search_query_daily" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "day" DATE NOT NULL,
    "term" TEXT NOT NULL,
    "searches" INTEGER NOT NULL DEFAULT 0,
    "zero_results" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "search_query_daily_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "banners_tenant_id_sort_idx" ON "banners"("tenant_id", "sort");

-- CreateIndex
CREATE INDEX "banners_tenant_id_published_starts_at_ends_at_idx" ON "banners"("tenant_id", "published", "starts_at", "ends_at");

-- CreateIndex
CREATE INDEX "trust_badges_tenant_id_sort_idx" ON "trust_badges"("tenant_id", "sort");

-- CreateIndex
CREATE INDEX "opening_hours_tenant_id_weekday_idx" ON "opening_hours"("tenant_id", "weekday");

-- CreateIndex
CREATE UNIQUE INDEX "opening_hours_tenant_id_weekday_key" ON "opening_hours"("tenant_id", "weekday");

-- CreateIndex
CREATE INDEX "store_stats_tenant_id_sort_idx" ON "store_stats"("tenant_id", "sort");

-- CreateIndex
CREATE INDEX "product_variants_tenant_id_product_id_sort_idx" ON "product_variants"("tenant_id", "product_id", "sort");

-- CreateIndex
CREATE INDEX "product_variants_tenant_id_stock_qty_idx" ON "product_variants"("tenant_id", "stock_qty");

-- CreateIndex
CREATE UNIQUE INDEX "product_variants_product_id_size_colour_key" ON "product_variants"("product_id", "size", "colour");

-- CreateIndex
CREATE INDEX "size_guide_entries_tenant_id_category_id_sort_idx" ON "size_guide_entries"("tenant_id", "category_id", "sort");

-- CreateIndex
CREATE UNIQUE INDEX "carriers_key_key" ON "carriers"("key");

-- CreateIndex
CREATE INDEX "carriers_hidden_sort_idx" ON "carriers"("hidden", "sort");

-- CreateIndex
CREATE INDEX "carrier_rates_carrier_id_sort_idx" ON "carrier_rates"("carrier_id", "sort");

-- CreateIndex
CREATE UNIQUE INDEX "carrier_rates_carrier_id_zone_name_key" ON "carrier_rates"("carrier_id", "zone_name");

-- CreateIndex
CREATE INDEX "tenant_carriers_tenant_id_sort_idx" ON "tenant_carriers"("tenant_id", "sort");

-- CreateIndex
CREATE UNIQUE INDEX "tenant_carriers_tenant_id_carrier_id_key" ON "tenant_carriers"("tenant_id", "carrier_id");

-- CreateIndex
CREATE INDEX "delivery_zones_tenant_id_sort_idx" ON "delivery_zones"("tenant_id", "sort");

-- CreateIndex
CREATE UNIQUE INDEX "delivery_zones_tenant_id_name_key" ON "delivery_zones"("tenant_id", "name");

-- CreateIndex
CREATE INDEX "delivery_zone_towns_tenant_id_zone_id_name_idx" ON "delivery_zone_towns"("tenant_id", "zone_id", "name");

-- CreateIndex
CREATE UNIQUE INDEX "delivery_zone_towns_tenant_id_normalised_key" ON "delivery_zone_towns"("tenant_id", "normalised");

-- CreateIndex
CREATE UNIQUE INDEX "tax_settings_tenant_id_key" ON "tax_settings"("tenant_id");

-- CreateIndex
CREATE INDEX "tax_settings_tenant_id_idx" ON "tax_settings"("tenant_id");

-- CreateIndex
CREATE INDEX "customers_tenant_id_last_order_at_idx" ON "customers"("tenant_id", "last_order_at");

-- CreateIndex
CREATE INDEX "customers_tenant_id_total_spent_agorot_idx" ON "customers"("tenant_id", "total_spent_agorot");

-- CreateIndex
CREATE UNIQUE INDEX "customers_tenant_id_phone_key" ON "customers"("tenant_id", "phone");

-- CreateIndex
CREATE INDEX "analytics_events_tenant_id_occurred_at_idx" ON "analytics_events"("tenant_id", "occurred_at");

-- CreateIndex
CREATE INDEX "analytics_events_tenant_id_kind_occurred_at_idx" ON "analytics_events"("tenant_id", "kind", "occurred_at");

-- CreateIndex
CREATE INDEX "analytics_daily_tenant_id_day_idx" ON "analytics_daily"("tenant_id", "day");

-- CreateIndex
CREATE UNIQUE INDEX "analytics_daily_tenant_id_day_path_key" ON "analytics_daily"("tenant_id", "day", "path");

-- CreateIndex
CREATE INDEX "section_dwell_daily_tenant_id_day_idx" ON "section_dwell_daily"("tenant_id", "day");

-- CreateIndex
CREATE UNIQUE INDEX "section_dwell_daily_tenant_id_day_section_key" ON "section_dwell_daily"("tenant_id", "day", "section");

-- CreateIndex
CREATE INDEX "search_query_daily_tenant_id_day_idx" ON "search_query_daily"("tenant_id", "day");

-- CreateIndex
CREATE INDEX "search_query_daily_tenant_id_zero_results_idx" ON "search_query_daily"("tenant_id", "zero_results");

-- CreateIndex
CREATE UNIQUE INDEX "search_query_daily_tenant_id_day_term_key" ON "search_query_daily"("tenant_id", "day", "term");

-- CreateIndex
CREATE INDEX "products_tenant_id_archived_at_published_sort_idx" ON "products"("tenant_id", "archived_at", "published", "sort");

-- AddForeignKey
ALTER TABLE "banners" ADD CONSTRAINT "banners_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "banners" ADD CONSTRAINT "banners_image_media_id_fkey" FOREIGN KEY ("image_media_id") REFERENCES "media"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trust_badges" ADD CONSTRAINT "trust_badges_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "opening_hours" ADD CONSTRAINT "opening_hours_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "store_stats" ADD CONSTRAINT "store_stats_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "size_guide_entries" ADD CONSTRAINT "size_guide_entries_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "size_guide_entries" ADD CONSTRAINT "size_guide_entries_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "carrier_rates" ADD CONSTRAINT "carrier_rates_carrier_id_fkey" FOREIGN KEY ("carrier_id") REFERENCES "carriers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tenant_carriers" ADD CONSTRAINT "tenant_carriers_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tenant_carriers" ADD CONSTRAINT "tenant_carriers_carrier_id_fkey" FOREIGN KEY ("carrier_id") REFERENCES "carriers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_zones" ADD CONSTRAINT "delivery_zones_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_zone_towns" ADD CONSTRAINT "delivery_zone_towns_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_zone_towns" ADD CONSTRAINT "delivery_zone_towns_zone_id_fkey" FOREIGN KEY ("zone_id") REFERENCES "delivery_zones"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tax_settings" ADD CONSTRAINT "tax_settings_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customers" ADD CONSTRAINT "customers_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "analytics_events" ADD CONSTRAINT "analytics_events_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "analytics_daily" ADD CONSTRAINT "analytics_daily_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "section_dwell_daily" ADD CONSTRAINT "section_dwell_daily_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "search_query_daily" ADD CONSTRAINT "search_query_daily_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- =============================================================================
-- Hand-written from here on — nothing below this line came from `prisma migrate diff`.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Row-level security on the fifteen new tenant-owned tables — the exact generic template from
--    prisma/migrations/20260809000100_rls_roles_and_guards/migration.sql, scoped to just these,
--    because that migration's own DO block already ran for every table that existed before it.
--
--    Invariant 1: isolation is enforced TWICE. The Prisma client extension sets the GUCs; this is
--    the layer that still refuses when the extension is bypassed, forgotten, or a raw query slips
--    through. `tests/integration/isolation.test.ts` proves it with the extension disabled, and
--    Phase 9 adds every table below to that proof.
--
--    `analytics_events` is in this list even though only the beacon route writes it and only the
--    rollup job reads it. A table nobody is "supposed to" read cross-tenant is exactly the table a
--    future reporting query reads cross-tenant by accident.
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  t text;
  tenant_tables text[] := ARRAY[
    'product_variants',
    'size_guide_entries',
    'banners',
    'trust_badges',
    'opening_hours',
    'store_stats',
    'customers',
    'delivery_zones',
    'delivery_zone_towns',
    'tenant_carriers',
    'tax_settings',
    'analytics_events',
    'analytics_daily',
    'section_dwell_daily',
    'search_query_daily'
  ];
BEGIN
  FOREACH t IN ARRAY tenant_tables LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);

    -- The generic template. Identical USING and WITH CHECK: a tenant may not read another
    -- tenant's row, and may not write one either.
    EXECUTE format($p$
      CREATE POLICY tenant_isolation ON %I
        FOR ALL TO app_web
        USING (
          tenant_id = current_setting('app.tenant_id', true)
          OR current_setting('app.actor_role', true) = 'super_admin'
        )
        WITH CHECK (
          tenant_id = current_setting('app.tenant_id', true)
          OR current_setting('app.actor_role', true) = 'super_admin'
        )
    $p$, t);

    -- app_system reads ids to fan out. It never writes a tenant-owned table — enforced by the
    -- GRANTs below, not merely by this policy.
    EXECUTE format($p$
      CREATE POLICY system_read ON %I FOR SELECT TO app_system USING (true)
    $p$, t);

    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO app_web', t);
    EXECUTE format('GRANT SELECT ON %I TO app_system', t);
  END LOOP;
END
$$;

-- -----------------------------------------------------------------------------
-- 2. The analytics rollup is the FIRST out-of-request job that must WRITE tenant-owned rows.
--
--    Every earlier job either only read (`lifecycle-sweep` fanning out ids) or wrote through
--    `withTenantTxn` as app_web. The rollup does the latter — it runs per tenant, inside
--    withTenantTxn, as app_web with `app.tenant_id` set — so the GRANTs above are exactly right and
--    app_system deliberately keeps SELECT only. Stated here because the temptation to "just let
--    app_system write the rollups, it's only counters" would hand a cross-tenant write path to the
--    one role whose read policy is `USING (true)`. Do not.
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
-- 3. carriers / carrier_rates — GLOBAL (prisma/GLOBAL_TABLES.md), following the exact shape
--    migration 0001 gave `plans` and `plan_features`: a platform catalogue is readable by every
--    web request (a merchant must see the carrier they were assigned) and writable by app_web,
--    with the super-admin-only route as the actual enforcement — src/server/delivery/carriers.ts.
--    app_system gets SELECT so a future report can count assignments without a write path.
--
--    No RLS: there is no tenant_id for the generic template to key on, and unlike `users` or
--    `sessions` there is nothing personal here to protect. A delivery company's public price list
--    is not a secret.
-- -----------------------------------------------------------------------------
GRANT SELECT ON "carriers", "carrier_rates" TO app_web, app_system;
GRANT INSERT, UPDATE, DELETE ON "carriers", "carrier_rates" TO app_web;

-- -----------------------------------------------------------------------------
-- 4. Database-level guards that do not depend on application code being correct — the same
--    philosophy as migration 0001 section 2 and migration 0004 section 3.
-- -----------------------------------------------------------------------------

-- Money is agorot, and agorot are not negative.
ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_amounts_nonneg" CHECK (
  "stock_qty" >= 0
  AND ("price_agorot_override" IS NULL OR "price_agorot_override" >= 0)
);

ALTER TABLE "products" ADD CONSTRAINT "products_phase9_amounts_nonneg" CHECK (
  "stock_qty" >= 0
  AND ("compare_at_price_agorot" IS NULL OR "compare_at_price_agorot" >= 0)
  AND ("low_stock_threshold" IS NULL OR "low_stock_threshold" >= 0)
);

ALTER TABLE "order_settings" ADD CONSTRAINT "order_settings_phase9_amounts_nonneg" CHECK (
  "cod_fee_agorot" >= 0
  AND ("cod_max_agorot" IS NULL OR "cod_max_agorot" >= 0)
  AND ("unlisted_town_fee_agorot" IS NULL OR "unlisted_town_fee_agorot" >= 0)
);

ALTER TABLE "delivery_zones" ADD CONSTRAINT "delivery_zones_fee_nonneg" CHECK ("fee_agorot" >= 0);
ALTER TABLE "carrier_rates" ADD CONSTRAINT "carrier_rates_fee_nonneg" CHECK ("fee_agorot" >= 0);

ALTER TABLE "customers" ADD CONSTRAINT "customers_totals_nonneg" CHECK (
  "orders_count" >= 0 AND "total_spent_agorot" >= 0
);

-- The stock invariant that matters. `track_and_block` promises the storefront will not oversell;
-- this is the backstop if the FOR UPDATE decrement in the order transaction is ever bypassed by a
-- plain Prisma `update`. It is NOT a substitute for the row lock — a CHECK cannot serialise two
-- concurrent readers — it is what turns a silent negative balance into a loud failed transaction.
ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_stock_not_negative"
  CHECK ("stock_qty" >= 0);

-- 0 = Sunday .. 6 = Saturday. A seventh day does not exist and an eighth row must not be
-- representable.
ALTER TABLE "opening_hours" ADD CONSTRAINT "opening_hours_weekday_range"
  CHECK ("weekday" >= 0 AND "weekday" <= 6);

-- "HH:mm", 24-hour, zero-padded. Times are wall-clock facts about a shop, stored as text on
-- purpose (see the model docblock) — which means the format is application discipline unless it is
-- checked here. NULL is allowed: a closed day has no hours.
ALTER TABLE "opening_hours" ADD CONSTRAINT "opening_hours_time_format" CHECK (
  ("opens_at"  IS NULL OR "opens_at"  ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$')
  AND ("closes_at" IS NULL OR "closes_at" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$')
);

-- מע"מ as basis points. 0-10000 covers 0% to 100%; anything outside it is a units mistake
-- (someone storing 17 or 0.17 instead of 1700), which is precisely the bug this catches.
ALTER TABLE "tax_settings" ADD CONSTRAINT "tax_settings_vat_range" CHECK (
  "vat_rate_basis_points" IS NULL
  OR ("vat_rate_basis_points" >= 0 AND "vat_rate_basis_points" <= 10000)
);

-- Analytics counters are counts.
ALTER TABLE "analytics_daily" ADD CONSTRAINT "analytics_daily_counts_nonneg" CHECK (
  "visitors" >= 0 AND "pageviews" >= 0 AND "product_views" >= 0 AND "whatsapp_clicks" >= 0
  AND "add_to_carts" >= 0 AND "checkout_starts" >= 0 AND "orders" >= 0
);

ALTER TABLE "section_dwell_daily" ADD CONSTRAINT "section_dwell_daily_counts_nonneg" CHECK (
  "views" >= 0 AND "total_dwell_ms" >= 0
);

-- A day's zero-result searches cannot exceed that day's searches. The rollup computes both from
-- the same rows, so a violation here means the rollup's arithmetic is wrong — which is a bug worth
-- failing loudly rather than a number worth displaying.
ALTER TABLE "search_query_daily" ADD CONSTRAINT "search_query_daily_counts_sane" CHECK (
  "searches" >= 0 AND "zero_results" >= 0 AND "zero_results" <= "searches"
);

-- Raw analytics rows carry no free-text identity. `dwell_ms` is clamped in the ingest route to
-- `platform_settings.analytics_max_dwell_ms`; this is the floor half of that clamp, and the reason
-- it is a CHECK is that a negative duration is not a small error, it is a sign the client's clock
-- was trusted.
ALTER TABLE "analytics_events" ADD CONSTRAINT "analytics_events_dwell_sane" CHECK (
  ("dwell_ms" IS NULL OR "dwell_ms" >= 0)
  AND ("result_count" IS NULL OR "result_count" >= 0)
);

-- A carrier key is a stable machine identifier, lowercase, and never Arabic — `name` is where the
-- Arabic display name lives. Same discipline as `Category.key` and `Plan.key`.
ALTER TABLE "carriers" ADD CONSTRAINT "carriers_key_slug_shape"
  CHECK ("key" ~ '^[a-z0-9][a-z0-9_-]*$');

-- The town match key is produced ONLY by `normaliseTownName()` (src/server/delivery/towns.ts),
-- which lowercases nothing (Arabic has no case) but does strip the ال prefix, fold أإآا to ا,
-- ة to ه, ى to ي, remove tatweel, and collapse whitespace. What this CHECK can enforce cheaply is
-- the part that is always true of its output regardless of script: no leading or trailing
-- whitespace, and never empty. A blank normalised key would match every unparseable address.
ALTER TABLE "delivery_zone_towns" ADD CONSTRAINT "delivery_zone_towns_normalised_trimmed" CHECK (
  length("normalised") > 0 AND "normalised" = btrim("normalised")
);

-- Platform-wide Phase 9 constants stay sane.
ALTER TABLE "platform_settings" ADD CONSTRAINT "platform_settings_phase9_nonneg" CHECK (
  "low_stock_threshold_default" >= 0
  AND "analytics_raw_retention_days" >= 1
  AND "analytics_max_dwell_ms" >= 1000
);
